stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${TOKEN} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY}/hello/gitlab-${CI_COMMIT_SHORT_SHA} .
    - docker push ${CI_REGISTRY}/hello/gitlab-${CI_COMMIT_SHORT_SHA}

deploy:
  stage: deploy
  tags:
    - shell
  only: 
    - main
  script:
  - docker pull ${CI_REGISTRY}/hello/gitlab-${CI_COMMIT_SHORT_SHA}
  - if [[ $(docker ps -a | grep -wc hellp) > 0 ]]; then docker rm -f hello; else echo Контейнер еще не был создан; fi
  - docker run -tid --name hello -p 5291:5290 ${CI_REGISTRY}/hello/gitlab-${CI_COMMIT_SHORT_SHA} 